theme: jekyll-theme-Dinky
title: Patrice's portfolio
description: Ajoutez cette page à vos favoris pour suivre les mises à jour de mes projets !
sass:  
  load_paths:    
    - _sass    
    - assets/css



